# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"\x0e\n\x0c\x45mptyRequest\"#\n\x0fUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"$\n\x12UserExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"D\n\x0eMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\x10MessagesResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\"<\n\x14\x44\x65leteMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\x05\"!\n\x10UserListResponse\x12\r\n\x05users\x18\x01 \x03(\t\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x82\x03\n\x0b\x43hatService\x12\x38\n\x0f\x43heckUserExists\x12\x10.UsernameRequest\x1a\x13.UserExistsResponse\x12+\n\x0cRegisterUser\x12\x10.RegisterRequest\x1a\t.Response\x12%\n\tLoginUser\x12\r.LoginRequest\x1a\t.Response\x12)\n\x0bSendMessage\x12\x0f.MessageRequest\x1a\t.Response\x12\x32\n\x0bGetMessages\x12\x10.UsernameRequest\x1a\x11.MessagesResponse\x12\x31\n\rDeleteMessage\x12\x15.DeleteMessageRequest\x1a\t.Response\x12-\n\tListUsers\x12\r.EmptyRequest\x1a\x11.UserListResponse\x12$\n\x08SaveData\x12\r.EmptyRequest\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=14
  _globals['_EMPTYREQUEST']._serialized_end=28
  _globals['_USERNAMEREQUEST']._serialized_start=30
  _globals['_USERNAMEREQUEST']._serialized_end=65
  _globals['_USEREXISTSRESPONSE']._serialized_start=67
  _globals['_USEREXISTSRESPONSE']._serialized_end=103
  _globals['_REGISTERREQUEST']._serialized_start=105
  _globals['_REGISTERREQUEST']._serialized_end=158
  _globals['_LOGINREQUEST']._serialized_start=160
  _globals['_LOGINREQUEST']._serialized_end=210
  _globals['_MESSAGEREQUEST']._serialized_start=212
  _globals['_MESSAGEREQUEST']._serialized_end=280
  _globals['_MESSAGESRESPONSE']._serialized_start=282
  _globals['_MESSAGESRESPONSE']._serialized_end=318
  _globals['_DELETEMESSAGEREQUEST']._serialized_start=320
  _globals['_DELETEMESSAGEREQUEST']._serialized_end=380
  _globals['_USERLISTRESPONSE']._serialized_start=382
  _globals['_USERLISTRESPONSE']._serialized_end=415
  _globals['_RESPONSE']._serialized_start=417
  _globals['_RESPONSE']._serialized_end=460
  _globals['_CHATSERVICE']._serialized_start=463
  _globals['_CHATSERVICE']._serialized_end=849
# @@protoc_insertion_point(module_scope)
